services:
  postgres:
    image: postgres:15-alpine
    container_name: text-match-postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: text_match_analyzer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d text_match_analyzer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
